fix(*): schema desc transformation in plugin forms
Kong/public-ui-components pull request #1021
Opened 2023-12-20 07:05 UTC by sumimakito

# Summary

This PR makes the plugin form use descriptions from backend schemas when descriptions are not defined in frontend schemas. It also fixes some current issues with tooltips.

### Tooltips for _schema_ fields

Example: `request-validator`

|Before|After|
|-|-|
|<img width="550" alt="Screenshot 2023-12-20 at 13 58 47" src="https://github.com/Kong/public-ui-components/assets/5277268/6b6d27f1-9a34-4d2a-8562-685b0b79d14b">|<img width="499" alt="Screenshot 2023-12-20 at 14 00 12" src="https://github.com/Kong/public-ui-components/assets/5277268/a99f26c0-b496-4249-ad9f-8ee58c078a29">|

### Tooltips for nested fields

Example: `rate-limiting-advanced`

|Before|After|
|-|-|
|<img width="439" alt="Screenshot 2023-12-20 at 13 59 12" src="https://github.com/Kong/public-ui-components/assets/5277268/392fcda1-769e-49bd-8083-d2154b6e9744">|<img width="606" alt="Screenshot 2023-12-20 at 13 59 44" src="https://github.com/Kong/public-ui-components/assets/5277268/af4da84b-d2ea-4c24-82ef-f5468c52e540">|

### Missing tooltips

Example: `jwt` (some descriptions are missing from Konnect API but available in the Gateway Admin API)

|Before|After|
|-|-|
|<img width="446" alt="Screenshot 2023-12-20 at 13 57 47" src="https://github.com/Kong/public-ui-components/assets/5277268/de8bbc64-9748-4a8b-a034-8b15d770f3cc">|<img width="554" alt="Screenshot 2023-12-20 at 14 00 47" src="https://github.com/Kong/public-ui-components/assets/5277268/cb41d7bf-ce6b-4e24-95df-d1ddde27305d">|

### Outdated tooltips

Example: `kafka-upstream`

<img width="376" alt="Screenshot 2023-12-20 at 13 57 31" src="https://github.com/Kong/public-ui-components/assets/5277268/87b0175c-18fe-4311-9a73-db3a680c33f0">

KAG-3347

2023-12-20 08:56 UTC, sumimakito commented
Note: although it seems that we are not using `packages/core/forms/src/forms/ACMEForm.vue` by default anymore, I just updated that component in case it is used

2023-12-20 15:06 UTC, kaiarrowood reviewed
This all makes sense to me, but I did not functional test 🚀

2023-12-20 15:07 UTC, kaiarrowood approved these changes

2023-12-20 21:57 UTC, adamdehaven requested changes
@sumimakito, @hl782 would like to test this before merge. I'm pulling the package into [this `khcp-ui` PR](https://github.com/Kong/khcp-ui/pull/7336); and blocking merge until he signs off (no actual issues).

2023-12-21 16:14 UTC, adamdehaven approved these changes
Verified by @hl782

2023-12-22 03:23 UTC, merged