feat(analytics-chart): experimenting with legend styling
Kong/public-ui-components pull request #1240
Opened 2024-03-13 22:57 UTC by mihai-peteu

# Summary

@filipgutica This is an attempt to simplify the Legend height conundrum, and keep it styled via pure CSS (thus allowing us to do away with the bound CSS variable). 

Using color squares instead of lines, and also left-aligning the legend (roughly in line w/ the Y-Axis labels)
<img width="713" alt="Screenshot 2024-03-19 at 11 36 51" src="https://github.com/Kong/public-ui-components/assets/103061463/a1e4f16d-3e31-4fdf-8db7-349b3c467d60">

#### Resources

- [Creating a package docs](https://github.com/Kong/public-ui-components/blob/main/docs/creating-a-package.md)

2024-03-27 17:17 UTC, filipgutica requested changes

2024-03-27 17:17 UTC, filipgutica commented on packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
> -const doesTheLegendWrap = () => {
I think we still need some of this code, just playing around in the sandbox I see some issues with legend items overlapping 

![image](https://github.com/Kong/public-ui-components/assets/6026470/07af6d15-f3a2-499c-9011-063d95a1a24d)

2024-03-27 23:21 UTC, filipgutica requested changes
Sometimes still overlapping in some situations and also sometimes not showing the second row

![image](https://github.com/Kong/public-ui-components/assets/6026470/3c6cde26-e291-4c5f-ada3-0dc9324a4136)

![image](https://github.com/Kong/public-ui-components/assets/6026470/45d4d6d4-0e82-4666-a953-a8f5506b5fa9)

Also, when it wraps to a new line, should there be more space between rows?
![image](https://github.com/Kong/public-ui-components/assets/6026470/a88a48f1-0c35-4779-aa94-f6c9f30d0efb)

2024-03-27 23:45 UTC, filipgutica commented on packages/analytics/analytics-chart/src/components/chart-plugins/ChartLegend.vue
> -      legendHeight.value = KUI_SPACE_110
May be we should still use 110 here? 🤔

2024-04-08 23:54 UTC, filipgutica requested changes
There's still some weirdness with the spacing of the legend items, some legend color tags also don't show up or are getting cut off?

On this branch
<img width="1138" alt="image" src="https://github.com/Kong/public-ui-components/assets/6026470/411d3775-6255-4079-a628-da96f6a2b749">


Vs on dev:
<img width="1136" alt="image" src="https://github.com/Kong/public-ui-components/assets/6026470/9e6488ca-dc52-4b0d-83bd-ecc2d074699f">

2024-06-24 19:13 UTC, mihai-peteu commented
Closing in favor of https://github.com/Kong/public-ui-components/pull/1462

But the `legendAsGrid` mixin could prove useful in the future...

2024-06-24 19:17 UTC, closed without merging