chore(deps): revert pinning monaco in core/expressions
Kong/public-ui-components pull request #1542
Opened 2024-08-08 04:08 UTC by sumimakito

# Summary

This pull request reverts:

- https://github.com/Kong/public-ui-components/pull/1354

The reason why we decided to pin `monaco-editor` for `core/expressions` was because the latest version by that time was causing errors. However, it seems we cannot reproduce those errors anymore with the latest version as of today. This pull request is to revert the previous change that pinned `monaco-editor`.

KM-390

2024-09-06 02:59 UTC, adamdehaven requested changes

2024-09-06 02:59 UTC, adamdehaven commented on renovate.json
> +    "pnpm": "8.6.11"
issue: this repository uses pnpm v9. I believe this constraint block should now be removed.

2024-09-06 07:11 UTC, Leopoldthecoder approved these changes

2024-09-10 07:43 UTC, adamdehaven approved these changes

2024-09-10 07:54 UTC, merged