fix(spec-renderer): correct path for the id to fix scrolling (TDX-2877)
Kong/public-ui-components pull request #156
Opened 2023-02-17 16:38 UTC by davidma415

# Summary
Swagger was doing some weird escaping on the path, so this replaces the space with an underscore instead (which is what the ID actually is being rendered with)

## PR Checklist

* [ ] **Naming & Structure:** the files and package structure use the conventions outlined in the [Creating a Package docs](https://github.com/Kong/public-ui-components/blob/main/docs/creating-a-package.md).
* [ ] **Tests pass:** check the output of all package unit and/or component tests.
  * [ ] If this PR is the result of a bug, test coverage was added accordingly.
* [ ] **Functional:** all changes do not break existing APIs, but if so, a BREAKING CHANGE commit is in place to bump the major version.
* [ ] **Conventional Commits** all commits follow the conventional commit standards [outlined in the main README](https://github.com/Kong/public-ui-components#committing-changes).
* [ ] **Docs:** includes a technically accurate README, and the docs have been updated accordingly based on the changes in this PR.

2023-02-21 14:47 UTC, adamdehaven commented on packages/portal/swagger-ui-web-component/src/utils.js
> +export const operationToSwaggerThingId = (operation) => {
suggestion: is it possible to provide a type interface for `operation`?

2023-02-21 16:23 UTC, andrewwylde requested changes
mostly nits but one change requested. Thanks for the work!

2023-02-21 17:15 UTC, davidma415 commented
@andrewwylde @adamdehaven so I was trying to refactor `utils.js` to be a TypeScript file, but I was missing the import of `helpers` from `swagger-client`. Once I added that back in, I was getting build errors since `helpers` isn't typed - hope we're okay with leaving it for now?

2023-02-21 17:51 UTC, adamdehaven submitted a review, later dismissed

2023-02-21 21:26 UTC, andrewwylde approved these changes

2023-02-22 01:22 UTC, andrewwylde approved these changes
Gr8, m8

2023-02-22 01:33 UTC, adamdehaven approved these changes
🚢

2023-02-22 01:46 UTC, andrewwylde commented on packages/portal/spec-renderer/src/components/SpecDetails.vue
> +    const newStr: string = decodeURIComponent(activeOperation.tag.trim().replaceAll(/\s/g, '%20'))
can you just add a note that this is the same logic from the other repo? I know they're tightly coupled.

2023-02-22 14:46 UTC, merged