feat(queryTime): support doing calculations in a specific TZ [MA-1916]
Kong/public-ui-components pull request #722
Opened 2023-08-18 18:43 UTC by adorack

- Avoid breaking the API; `tz` is an optional param.
- Add many test cases.

# Summary

## PR Checklist

* [ ] **Naming & Structure:** the files and package structure use the conventions outlined in the [Creating a Package docs](https://github.com/Kong/public-ui-components/blob/main/docs/creating-a-package.md).
* [ ] **Tests pass:** check the output of all package unit and/or component tests.
  * [ ] If this PR is the result of a bug, test coverage was added accordingly.
* [ ] **Functional:** all changes do not break existing APIs, but if so, a BREAKING CHANGE commit is in place to bump the major version.
* [ ] **Conventional Commits** all commits follow the conventional commit standards [outlined in the main README](https://github.com/Kong/public-ui-components#committing-changes).
* [ ] **Docs:** includes a technically accurate README, and the docs have been updated accordingly based on the changes in this PR.

2023-08-18 18:58 UTC, adorack commented
Reverted to draft to figure out why some tests fail in CI.

2023-08-18 23:03 UTC, mihai-peteu requested changes
Looks good, nothing broken in konnect. Just a quick question on an unused param.

2023-08-20 18:38 UTC, adorack commented on packages/analytics/analytics-utilities/src/timeframes.ts
> +  rawEnd(_tz?: string): Date {
Done.

2023-08-20 18:43 UTC, adorack commented on packages/analytics/analytics-utilities/src/timeframes.ts
> +  rawEnd(_tz?: string): Date {
Ah, never mind, I remember why I did this now -- the subclasses need it, and this is the base class, so I still need to declare it.  (If `TimeFrames` was implemented as an interface, I probably could leave it out, but I'd rather not change how the types are set up right now.)

Ignored the lint error instead.

2023-08-21 17:02 UTC, mihai-peteu approved these changes

2023-08-21 17:07 UTC, adamdehaven approved these changes

2023-08-21 17:10 UTC, merged